stages:
  preprocess:
    cmd: python -m src.data.prepare_data_new
    deps:
      - src/data/prepare_data_new.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/train_clean.csv
      - data/processed/test_clean.csv

  train:
    cmd: python -m src.train
    deps:
      - src/config.py
      - conf
      - src/models/Different_models.py
      - src/train.py
      - data/processed/train_clean.csv
    outs:
      - models/model.pkl
      - reports/train_reports/train_info.json

  predict:
    cmd: python -m src.predict
    deps:
      - src/config.py
      - conf
      - src/predict.py
      - models/model.pkl
      - data/processed/test_clean.csv
    outs:
      - data/predictions/submission.csv
